### ISSUE TITLE
Can't Connect Multiple Servers To Authenticated Sockets

### ISSUE THREAD

**Issue by CharlieOrlando** [cobinhood/api-public#38]
I run two servers (one for trading, one for testing/logging everything), and they both use the authenticated websocket to monitor my orders. This has never been a problem before, but just 30 minutes ago, I started receiving a 429 error when attempting to connect both to the order websocket.

**Comment by CharlieOrlando** [comment]
Solved the issue (sort-of). I had to close one of my Cobinhood tabs on my browser. I've had several Cobinhood tabs open at once before, though, and this has never been a problem.

**Comment by kpei** [comment]
Do you find that connecting to multiple sockets is faster than subscribing to multiple areas within one socket?

**Comment by somghosh** [comment]
@CharlieOrlando  - wanted to ask you this as clearly in the first post you have been able to authenticate via websockets

I am looking into this page - https://cobinhood.github.io/api-public/#websocket-v2 however, there seems to be no instruction on how to authenticate into an account when connecting via websockets

Can you kindly point me to the right place? Seems this was missed out in this documentation

Thanks
