### ISSUE TITLE
cobinhood RESTful API tickers not working

### ISSUE THREAD

**Issue by kamisan118** [cobinhood/api-public#4]
tested https://api.cobinhood.com/v1/market/tickers/BTC-USD

got {"success":true,"result":{"ticker":{"trading_pair_id":"BTC-USD","timestamp":1514182560000,"24h_high":"10011.1","24h_low":"10011.1","24h_open":"10011.1","24h_volume":"0.0076","last_trade_price":"10011.1","highest_bid":"10011.1","lowest_ask":"10011.1"}}}

where lowest_ask and highest_bid are both wrong. They are always the same and also they're not the best bid/ask price in the orderbook.

**Comment by aitjcize** [comment]
Fixed in the latest release.
