### ISSUE TITLE
websocket orderbook closes connection despite pinging to stay alive

### ISSUE THREAD

**Issue by kpei** [cobinhood/api-public#43]
I'm currently retrieving the orderbook for three pairs and pinging every 30 seconds to stay alive with the server.  However, there are still cases where the connection gets closed on me from the server side for no reason.  

Anyone else get this issue?

**Comment by passa1248** [comment]
Some problem, looking the site also this continue to reconnect after close:
![image](https://user-images.githubusercontent.com/19681865/38319515-40387478-3832-11e8-9a47-6e25bec9b5ca.png)
