### ISSUE TITLE
getting parameter_error when placing order

### ISSUE THREAD

**Issue by oxofrembl** [cobinhood/api-public#55]
hi,
i am using the `https://api.cobinhood.com/v1/trading/orders/` to place an order with following parameters:
`{trading_pair_id=LTC-BTC, side=ask, type=limit, price=0.02, size=1.0}`

I have enough funds on my account but i receive:
`{success=false, error={error_code=parameter_error}, request_id=...}`

**Comment by huangjosh** [comment]
@oxofrembl Did you solve this issue? I came across similar problem.
