### ISSUE TITLE
Socket: Cannot subscribe socket to orderbook

### ISSUE THREAD

**Issue by MHamburg** [cobinhood/api-public#8]
Connection used: feed.cobinhood.com

In the docs it states that the socket connection for the orderbook requires a subscribe request formated as follows:

{
  "action": 'subscribe',
  "type": 'book',
  "trading_pair_id": TRADING_PAIR_ID
}

When we send a request, we get the following result:

{"event":"error","trading_pair_id":"BAT-BTC","type":"book","code":"4003","message":"subscribe_failed"}

Any ideas what we might be doing wrong? (other types work correctly: trade and ticker)

**Comment by DSoane** [comment]
Hi MHamburg,

I haven't even got that far. When try and upgrade from HTTP to WebSockets I get error 501 - Not Implemented.

Do you actually connect correctly to websockets? If so, what are you using?

Dave.

**Comment by MHamburg** [comment]
@DSoane,
I use the same feed as they use on their webapp: wss://feed.cobinhood.com/ws

@cob-dev 
I also found the issue debugging the webapp, should have been "order-book" instead of "book", so please adjust the docs for this?
